Fix TypeScript errors
Fixes the following TypeScript errors:
- src/components/layout.tsx(14,17): error TS2339: Property 'isLoading' does not exist on type 'AuthState'.
- src/providers/AuthProvider.tsx(87,11): error TS2353: Object literal may only specify known properties, and 'name' does not exist in type 'User'.
- src/providers/AuthProvider.tsx(104,13): error TS2353: Object literal may only specify known properties, and 'name' does not exist in type 'User'.